/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import java.awt.BorderLayout;
import javax.swing.JOptionPane;

/**
 *
 * @author ROBBY
 */
public class jfHome extends javax.swing.JFrame {

    /**
     * Creates new form jfHome
     */
    jpMasterSales jpMasterSales = new jpMasterSales();
    jpMasterKategori jpMasterKategori = new jpMasterKategori();
    jpMasterBarang jpMasterBarang = new jpMasterBarang();
    public jfHome() {
        initComponents();
           
          
        jpMasterSales.setSize(jPanelHome.getWidth(),jPanelHome.getHeight());
        jPanelHome.add(jpMasterSales,BorderLayout.CENTER);
      
        jpMasterKategori.setSize(jPanelHome.getWidth(),jPanelHome.getHeight());
        jPanelHome.add(jpMasterKategori,BorderLayout.CENTER);
        
        jpMasterBarang.setSize(jPanelHome.getWidth(),jPanelHome.getHeight());
        jPanelHome.add(jpMasterBarang,BorderLayout.CENTER);
        
        //jPanelHome.revalidate();
        jpMasterSales.setVisible(false);
        jpMasterKategori.setVisible(false);
        jpMasterBarang.setVisible(false);
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelHome = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMnuMaster = new javax.swing.JMenu();
        jMnuSales = new javax.swing.JMenuItem();
        jMnuKategori = new javax.swing.JMenuItem();
        jMnuBarang = new javax.swing.JMenuItem();
        jMnuList = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("iTOKO");
        setPreferredSize(new java.awt.Dimension(1920, 1080));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        javax.swing.GroupLayout jPanelHomeLayout = new javax.swing.GroupLayout(jPanelHome);
        jPanelHome.setLayout(jPanelHomeLayout);
        jPanelHomeLayout.setHorizontalGroup(
            jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 959, Short.MAX_VALUE)
        );
        jPanelHomeLayout.setVerticalGroup(
            jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 414, Short.MAX_VALUE)
        );

        jMnuMaster.setText("Master");

        jMnuSales.setText("Sales");
        jMnuSales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuSalesActionPerformed(evt);
            }
        });
        jMnuMaster.add(jMnuSales);

        jMnuKategori.setText("Kategori");
        jMnuKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuKategoriActionPerformed(evt);
            }
        });
        jMnuMaster.add(jMnuKategori);

        jMnuBarang.setText("Barang");
        jMnuBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuBarangActionPerformed(evt);
            }
        });
        jMnuMaster.add(jMnuBarang);

        jMenuBar1.add(jMnuMaster);

        jMnuList.setText("List");
        jMenuBar1.add(jMnuList);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        setExtendedState(jfHome.MAXIMIZED_BOTH);
    }//GEN-LAST:event_formWindowOpened

    private void jMnuSalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuSalesActionPerformed
        // TODO add your handling code here:
        //JOptionPane.showMessageDialog(null,"Test") ;
        jpMasterSales.setVisible(true);
        jpMasterKategori.setVisible(false);
        jpMasterBarang.setVisible(false);
        
    }//GEN-LAST:event_jMnuSalesActionPerformed

    private void jMnuKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuKategoriActionPerformed
        // TODO add your handling code here:
        jpMasterKategori.setVisible(true);
        jpMasterSales.setVisible(false);
        jpMasterBarang.setVisible(false);
    }//GEN-LAST:event_jMnuKategoriActionPerformed

    private void jMnuBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuBarangActionPerformed
        // TODO add your handling code here:
     
        jpMasterBarang.revalidate();
        jpMasterBarang.validate();
        jpMasterBarang.setVisible(true);
        jpMasterSales.setVisible(false);
        jpMasterKategori.setVisible(false);
    }//GEN-LAST:event_jMnuBarangActionPerformed


    /**
     * @param args the command line arguments
     */
        
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfHome().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMnuBarang;
    private javax.swing.JMenuItem jMnuKategori;
    private javax.swing.JMenu jMnuList;
    private javax.swing.JMenu jMnuMaster;
    private javax.swing.JMenuItem jMnuSales;
    private javax.swing.JPanel jPanelHome;
    // End of variables declaration//GEN-END:variables
}
